{
 "title": "JSON RPC Relay",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg. Latency (ms)",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg (rate(rpc_relay_method_response_sum{ namespace=\"$namespace\"}[1m])) / avg (rate(rpc_relay_method_response_count{ namespace=\"$namespace\"}[1m]))",
       "legendFormat": "Relay"
      },
      {
       "expr": "avg(rate(rpc_relay_mirror_response_sum{ namespace=\"$namespace\"}[1m]))/avg(rate(rpc_relay_mirror_response_count{ namespace=\"$namespace\"}[1m]))",
       "legendFormat": "Mirror Node"
      }
     ]
    },
    {
     "title": "Avg. Latency (ms)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 17, "x": 7, "y": 1 },
     "targets": [
      {
       "expr": "avg (rate(rpc_relay_method_response_sum{ namespace=\"$namespace\"}[1m])) / avg (rate(rpc_relay_method_response_count{ namespace=\"$namespace\"}[1m]))",
       "legendFormat": "Relay"
      },
      {
       "expr": "avg(rate(rpc_relay_mirror_response_sum{ namespace=\"$namespace\"}[1m]))/avg(rate(rpc_relay_mirror_response_count{ namespace=\"$namespace\"}[1m]))",
       "legendFormat": "Mirror Node"
      }
     ]
    },
    {
     "title": "Latest Requests (RPS)",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1825 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_method_response_count{ namespace=\"$namespace\"}[1m]))",
       "legendFormat": "Relay"
      },
      {
       "expr": "sum(rate(rpc_relay_mirror_response_count{ namespace=\"$namespace\"}[1m]))",
       "legendFormat": "Mirror Node"
      }
     ]
    },
    {
     "title": "Requests (RPS)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 17, "x": 7, "y": 1825 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_method_response_count{ namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "Relay"
      },
      {
       "expr": "sum(rate(rpc_relay_mirror_response_count{ namespace=\"$namespace\"}[1m]))",
       "legendFormat": "Mirror Node"
      }
     ]
    }
   ]
  },
  {
   "title": "Relay Details - Volume, RPS, Usage and Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg. Latency (ms)",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(rate(rpc_relay_method_response_sum{namespace=\"$namespace\"}[1m]))/avg(rate(rpc_relay_method_response_count{namespace=\"$namespace\"}[1m]))",
       "legendFormat": "Mirror Node"
      }
     ]
    },
    {
     "title": "Relay Avg. Latency (ms)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 19, "x": 5, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(rate(rpc_relay_method_response_sum{namespace=\"$namespace\"}[$__rate_interval]))/avg(rate(rpc_relay_method_response_count{namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "Avg. Latency"
      }
     ]
    },
    {
     "title": "Relay Response Latency (ms) by Path",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "topk(6,sum by (method) (rate(rpc_relay_method_response_sum{ namespace=\"$namespace\"}[1m])) / sum by (method) (rate(rpc_relay_method_response_count{ namespace=\"$namespace\"}[1m])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Relay - Requests (RPS)",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_method_response_count{ namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "Relay Latency"
      }
     ]
    },
    {
     "title": "Relay - Requests (RPS)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 16, "x": 4, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_method_response_count{ namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "Relay Latency"
      }
     ]
    },
    {
     "title": "Relay - Requests Cummulative (Units)",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(rpc_relay_method_response_count{ namespace=\"$namespace\"}[$__range]))",
       "legendFormat": "Relay Latency"
      }
     ]
    },
    {
     "title": "Failure Request Rate",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_method_response_count{ namespace=\"$namespace\", statusCode!=\"200\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Failed Request Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 4, "y": 26 },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_method_response_bucket{ namespace=\"$namespace\", statusCode!=\"200\", statusCode!=\"400\"}[$__rate_interval]))",
       "legendFormat": "Failed Request RPS"
      }
     ]
    },
    {
     "title": "Failure %",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(rpc_relay_method_response_count{ namespace=\"$namespace\", statusCode!=\"200\", statusCode!=\"400\"}[$__range]))/sum(increase(rpc_relay_method_response_count{ namespace=\"$namespace\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Failure Total Count",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(rpc_relay_method_response_count{ namespace=\"$namespace\", statusCode!=\"200\", statusCode!=\"400\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Relay - Requests (RPS) by Method",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_method_response_count{ namespace=\"$namespace\"}[$__rate_interval])) by (method)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Requests to API by MethodName",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(15,  sum by(method)(increase(rpc_relay_method_response_count{namespace=\"$namespace\"}[$__range])))",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Failed Requests to API by MethodName",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(method)(increase(rpc_relay_method_response_count{namespace=\"$namespace\",statusCode!=\"200\"}[$__range]))",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Cumulative Requests by Path (units)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 52 },
     "targets": [
      {
       "expr": "sum by(method)(increase(rpc_relay_method_response_count{namespace=\"$namespace\"}[$__range]))",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "Failed Relay Requests By Status and Method (Units)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 62 },
     "targets": [
      {
       "expr": "sum(increase(rpc_relay_method_response_count{ namespace=\"$namespace\", statusCode!=\"200\"}[$__range])) by (statusCode, method)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Relay - Timeout Requests (RPS)",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"+Inf\"}[$__rate_interval]) - ignoring(le) rate(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"30000\"}[$__rate_interval]))",
       "legendFormat": "Relay Latency"
      }
     ]
    },
    {
     "title": "Relay - Requests Above 30s - Timeout",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 4, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"+Inf\"}[$__rate_interval]) - ignoring(le) rate(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"30000\"}[$__rate_interval]))",
       "legendFormat": "Relay Latency"
      }
     ]
    },
    {
     "title": "Relay - Timeout Requests %",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 16, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"+Inf\"}[$__range]) - ignoring(le) increase(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"30000\"}[$__range])) / sum(increase(rpc_relay_method_response_count{ namespace=\"$namespace\"}[$__range]))",
       "legendFormat": "Relay Latency"
      }
     ]
    },
    {
     "title": "Relay - Timeout Requests Cummulative (Units)",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"+Inf\"}[$__range]) - ignoring(le) increase(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"30000\"}[$__range]))",
       "legendFormat": "Relay Latency"
      }
     ]
    },
    {
     "title": "Relay - 60s latency Requests (RPS)",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"+Inf\"}[$__rate_interval]) - ignoring(le) rate(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"60000\"}[$__rate_interval]))",
       "legendFormat": "Relay Latency"
      }
     ]
    },
    {
     "title": "Relay - Requests Above 60s - Timeout",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 4, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"+Inf\"}[$__rate_interval]) - ignoring(le) rate(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"60000\"}[$__rate_interval]))",
       "legendFormat": "Relay Latency"
      }
     ]
    },
    {
     "title": "Relay - 60s Latency Requests %",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 16, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"+Inf\"}[$__range]) - ignoring(le) increase(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"60000\"}[$__range])) / sum(increase(rpc_relay_method_response_count{ namespace=\"$namespace\"}[$__range]))",
       "legendFormat": "Relay Latency"
      }
     ]
    },
    {
     "title": "Relay - 60s Latency Requests Cummulative (Units)",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"+Inf\"}[$__range]) - ignoring(le) increase(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"60000\"}[$__range]))",
       "legendFormat": "Relay Latency"
      }
     ]
    },
    {
     "title": "Relay - Requests By Pod (RPS)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_method_response_count{ namespace=\"$namespace\"}[$__rate_interval]))by(pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Relay - Requests below 5s Latency (RPS)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "topk(6,sum(rate(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"5000\"}[$__rate_interval])) by (method))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Relay - Requests above 5s Latency (RPS)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 91 },
     "targets": [
      {
       "expr": "topk(6,sum(rate(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"+Inf\"}[1m]) - ignoring(le) rate(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"5000\"}[1m])) by (method))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Relay - Requests between 5s and 10s Latency (RPS)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 100 },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"10000\"}[1m]) - ignoring(le) rate(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"5000\"}[1m])) by (method)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Relay - Requests above 10s Latency (RPS)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 100 },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"+Inf\"}[1m]) - ignoring(le) rate(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"10000\"}[1m])) by (method)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Relay Requests by Status Code (excluding 200)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 109 },
     "targets": [
      {
       "expr": "sum by(statusCode)(increase(rpc_relay_method_response_count{namespace=\"$namespace\",statusCode!=\"200\"}[$__range]))",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "Requests by Path (units) - Per day over the month",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 119 },
     "targets": [
      {
       "expr": "topk(15,sum by(method)(increase(rpc_relay_method_response_count{namespace=\"$namespace\"}[1d])))",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "Cache  Size By Pod",
     "type": "timeseries",
     "description": "Amount of Keys that are being stored in  the Cache by POD",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 129 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rpc_relay_cache{method=\"\", key=\"\",  namespace=\"$namespace\"}) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Cache Hits by Method",
     "type": "timeseries",
     "description": "Amount of Cache Hits (Found and returned)",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 129 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(rpc_cache_service_methods_counter{ namespace=\"$namespace\"}[$__range])) by (method)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "IP Rate Limiter by Method",
     "type": "barchart",
     "description": "Amount of times the IP Rate Limited has limited a request by method.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 138 },
     "targets": [
      {
       "expr": "increase(rpc_relay_ip_rate_limit{namespace=\"$namespace\"}[$__range])",
       "legendFormat": "{{methodName}}"
      }
     ]
    },
    {
     "title": "Hbar Rate Limiter by Method",
     "type": "barchart",
     "description": "Amount of times the Hbar Rate Limited has limited a request grouped by method.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 138 },
     "targets": [
      {
       "expr": "sum(increase(rpc_relay_hbar_rate_limit{ namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "{{methodName}}"
      }
     ]
    }
   ]
  },
  { "title": "Ethereum RPC Execution Methods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Average Reponse Latency (ms)",
   "type": "gauge",
   "description": "The average response latency (in milliseconds) for eth_call and eth_sendRawTransaction requests.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "# Calculate the average rate of `rpc_relay_method_response_sum` grouped by `method`\navg(rate(rpc_relay_method_response_sum{\n  namespace=\"$namespace\", \n  method=~\"eth_call|eth_sendRawTransaction\"\n}[1m])) by (method) \n/\n# Divide by the average rate of `rpc_relay_method_response_count` grouped by `method`\navg(rate(rpc_relay_method_response_count{\n  namespace=\"$namespace\", \n  method=~\"eth_call|eth_sendRawTransaction\"\n}[1m])) by (method)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Response Latency (ms)",
   "type": "timeseries",
   "description": "Latency Timeline for eth_call and eth_sendRawTransaction Requests",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "# Calculate the average rate of `rpc_relay_method_response_sum` grouped by `method`\navg(rate(rpc_relay_method_response_sum{\n  namespace=\"$namespace\", \n  method=~\"eth_call|eth_sendRawTransaction\"\n}[1m])) by (method) \n/\n# Divide by the average rate of `rpc_relay_method_response_count` grouped by `method`\navg(rate(rpc_relay_method_response_count{\n  namespace=\"$namespace\", \n  method=~\"eth_call|eth_sendRawTransaction\"\n}[1m])) by (method)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Request Rate (RPS)",
   "type": "gauge",
   "description": "The number of eth_call and eth_sendRawTransaction requests processed by the Relay per second, providing insights into the overall request throughput.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "# Calculate the sum rate of `rpc_relay_method_response_count` grouped by `method`\nsum(rate(\n  rpc_relay_method_response_count{\n    namespace=\"$namespace\", \n    method=~\"eth_call|eth_sendRawTransaction\"\n  }[$__rate_interval]\n)) by (method)\n\n# OR clause: Ensures all desired methods (\"eth_call\" and \"eth_sendRawTransaction\") appear in the result\nor\n\n# Placeholder query: Generates 0 values for all desired methods even if there is no data for them\nsum(\n  0 * rpc_relay_method_response_count{\n    namespace=\"$namespace\", \n    method=~\"eth_call|eth_sendRawTransaction\"\n  }\n) by (method)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Request Rate (RPS)",
   "type": "timeseries",
   "description": "The number of eth_call and eth_sendRawTransaction requests processed by the Relay per second, providing insights into the overall request throughput.",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "# Calculate the sum rate of `rpc_relay_method_response_count` grouped by `method`\nsum(rate(\n  rpc_relay_method_response_count{\n    namespace=\"$namespace\", \n    method=~\"eth_call|eth_sendRawTransaction\"\n  }[$__rate_interval]\n)) by (method)\n\n# OR clause: Ensures all desired methods (\"eth_call\" and \"eth_sendRawTransaction\") appear in the result\nor\n\n# Placeholder query: Generates 0 values for all desired methods even if there is no data for them\nsum(\n  0 * rpc_relay_method_response_count{\n    namespace=\"$namespace\", \n    method=~\"eth_call|eth_sendRawTransaction\"\n  }\n) by (method)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Request Count",
   "type": "stat",
   "description": "The total number of eth_call and eth_sendRawTransaction requests processed.",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "# Primary query: Calculates the total count of all responses for each method\nsum(\n  increase(\n    rpc_relay_method_response_count{\n      namespace=\"$namespace\", \n      method=~\"eth_call|eth_sendRawTransaction\"\n    }[$__range]\n  )\n) by (namespace, method)\n\n# OR clause: Ensures all desired methods (\"eth_call\" and \"eth_sendRawTransaction\") appear in the result\nor\n\n# Placeholder query: Generates 0 values for all desired methods even if there is no data for them\nsum(\n  0 * rpc_relay_method_response_count{\n    namespace=\"$namespace\", \n    method=~\"eth_call|eth_sendRawTransaction\"\n  }\n) by (namespace, method)\n",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Total Failed Requests",
   "type": "stat",
   "description": "Total failed eth_call and eth_sendRawTransaction requests (non-200 & non-400 status codes).",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "# Primary query: Calculates the total count of non-200 and non-400 responses\nsum(\n  increase(\n    rpc_relay_method_response_count{\n      namespace=\"$namespace\", \n      statusCode!=\"200\", \n      statusCode!=\"400\", \n      method=~\"eth_call|eth_sendRawTransaction\"\n    }[$__range]\n  )\n) by (namespace, method)\n\n## OR clause: Ensures all desired methods (\"eth_call\" and \"eth_sendRawTransaction\") appear in the result\nor\n\n## Placeholder query: Generates 0 values for all desired methods even if there is no data for them\nsum(\n  0 * rpc_relay_method_response_count{\n    namespace=\"$namespace\", \n    method=~\"eth_call|eth_sendRawTransaction\"\n  }\n) by (namespace, method)\n",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Failure Rate Percentage",
   "type": "stat",
   "description": "Percentage of failed eth_call and eth_sendRawTransaction requests (non-200 && non-400 status codes).",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "# Numerator: Total count of non-200 responses for each method\n(\n  sum(\n    increase(\n      rpc_relay_method_response_count{\n        namespace=\"$namespace\", \n        statusCode!=\"200\",\n        statusCode!=\"400\", \n        method=~\"eth_call|eth_sendRawTransaction\"\n      }[$__range]\n    )\n  ) by (namespace, method)\n  # Ensures all methods appear with 0 if no data exists for them\n  or\n  sum(\n    0 * rpc_relay_method_response_count{\n      namespace=\"$namespace\", \n      method=~\"eth_call|eth_sendRawTransaction\"\n    }\n  ) by (namespace, method)\n)\n\n# Divided by\n\n# Denominator: Total count of all responses (regardless of status code) for each method\n/\n(\n  sum(\n    increase(\n      rpc_relay_method_response_count{\n        namespace=\"$namespace\", \n        method=~\"eth_call|eth_sendRawTransaction\"\n      }[$__range]\n    )\n  ) by (namespace, method)\n  # Ensures all methods appear with 0 if no data exists for them\n  or\n  sum(\n    0 * rpc_relay_method_response_count{\n      namespace=\"$namespace\", \n      method=~\"eth_call|eth_sendRawTransaction\"\n    }\n  ) by (namespace, method)\n)\n",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Failed eth_call Requests by Status Code",
   "type": "piechart",
   "description": "The total count of failed eth_call requests, categorized by status code, indicating the types of errors encountered.",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(rpc_relay_method_response_count{ namespace=\"$namespace\", statusCode!=\"200\", method=\"eth_call\"}[$__range])) by (statusCode)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed eth_call Requests by Status Code Over Time",
   "type": "timeseries",
   "description": "The total count of failed eth_call requests, categorized by status code, indicating the types of errors encountered over time.",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 32 },
   "targets": [
    {
     "expr": "sum(increase(rpc_relay_method_response_count{ namespace=\"$namespace\", statusCode!=\"200\", method=\"eth_call\"}[$__range])) by (statusCode)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed eth_sendRawTransaction Requests by Status Code",
   "type": "piechart",
   "description": "The total count of failed eth_sendRawTransaction requests, categorized by status code, indicating the types of errors encountered.",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(rpc_relay_method_response_count{ namespace=\"$namespace\", statusCode!=\"200\", method=\"eth_sendRawTransaction\"}[$__range])) by (statusCode)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed eth_sendRawTransaction Requests by Status Code Over Time",
   "type": "timeseries",
   "description": "The total count of failed eth_sendRawTransaction requests, categorized by status code, indicating the types of errors encountered over time.",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 41 },
   "targets": [
    {
     "expr": "sum(increase(rpc_relay_method_response_count{ namespace=\"$namespace\", statusCode!=\"200\", method=\"eth_sendRawTransaction\"}[$__range])) by (statusCode)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Hbar Rate Limit Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Relay Operator Balance - (ℏ)",
   "type": "timeseries",
   "description": "The total HBAR balance of the Relay Operator's account. ",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by(accountId)  (rpc_relay_operator_balance{namespace=\"$namespace\", mode!=\"QUERY\", mode!=\"TRANSACTION\"} / 100000000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HBAR Rate Limit Counter",
   "type": "stat",
   "description": "The total occurrences of HBAR rate limit violations encountered by the Relay instance in the $namespace.",
   "gridPos": { "h": 9, "w": 5, "x": 10, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rpc_relay_hbar_rate_limit{methodName=\"eth_sendRawTransaction\", mode=\"TRANSACTION\", namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total HBAR Burnt for $namespace - (ℏ)",
   "type": "stat",
   "description": "The total amount of HBAR consumed by the operator across all activities and operations in $namespace in the course of 24 hours. ",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(namespace) (8000 - rpc_relay_hbar_rate_remaining{namespace=\"$namespace\"} / 100000000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total HBAR Burnt By Server - HTTP (ℏ)",
   "type": "stat",
   "description": "The total HBAR burnt by the operator across all pods in the hedera-json-rpc-relay container in the course of 24 hours.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(namespace, container) (8000 - rpc_relay_hbar_rate_remaining{namespace=\"$namespace\", container=\"hedera-json-rpc-relay\"} / 100000000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total HBAR Burnt By Pod - HTTP (ℏ)",
   "type": "timeseries",
   "description": "The total HBAR burned by the operator in each pod of the hedera-json-rpc-relay container in the course of 24 hours.",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(namespace, pod) (8000 - rpc_relay_hbar_rate_remaining{namespace=\"$namespace\", container=\"hedera-json-rpc-relay\"} / 100000000)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total HBAR Burnt By Server - WS (ℏ)",
   "type": "stat",
   "description": "The total HBAR burnt by the operator across all pods in the json-rpc-relay-websocket container in the course of 24 hours.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 69 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(namespace, container) (8000 - rpc_relay_hbar_rate_remaining{namespace=\"$namespace\", container=\"json-rpc-relay-websocket\"} / 100000000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total HBAR Burnt By Pod - WS (ℏ)",
   "type": "timeseries",
   "description": "The total HBAR burned by the operator in each pod of the json-rpc-relay-websocket container in the course of 24 hours.",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(namespace, pod) (8000 - rpc_relay_hbar_rate_remaining{namespace=\"$namespace\", container=\"json-rpc-relay-websocket\"} / 100000000)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total Unique HBAR Spending Plans - BASIC",
   "type": "stat",
   "description": "The total number of unique BASIC HBAR spending plans in the course of 24 hours.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 78 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(namespace, container) (unique_spending_plans_counter_basic{namespace=\"$namespace\"})",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Total Unique HBAR Spending Plans - EXTENDED",
   "type": "stat",
   "description": "The total number of unique EXTENDED HBAR spending plans in the course of 24 hours.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 78 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(namespace, container) (unique_spending_plans_counter_extended{namespace=\"$namespace\"})",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Total Unique HBAR Spending Plans - PRIVILEGED",
   "type": "stat",
   "description": "The total number of unique PRIVILEGED HBAR spending plans in the course of 24 hours.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 78 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(namespace, container) (unique_spending_plans_counter_privileged{namespace=\"$namespace\"})",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Usage - Hbar Account and Burn Rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 },
   "collapsed": true,
   "panels": [
    {
     "title": "Hbar Spent per Day over the last Month By Mode - Regenerated",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1035 },
     "targets": [
      {
       "expr": "sum(increase(rpc_relay_consensusnode_response_sum{ namespace=\"$namespace\"}[1d])) by(mode) / 100000000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Relay Operator Balance Burn Rate over 1 day(ℏ)",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1035 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "abs(delta(HIERONET_account_balance{account_id=\"0.0.995584\", network=\"$namespace\"}[1d]) / 100000000)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Operator Cost  (ℏ) by Mode",
     "type": "stat",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1445 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (mode)(increase(rpc_relay_consensusnode_response_sum{ namespace=\"$namespace\"}[$__range])) / -100000000",
       "legendFormat": "{{mode}}"
      }
     ]
    },
    {
     "title": "Consensus Node (txns) Calls by Mode",
     "type": "stat",
     "gridPos": { "h": 8, "w": 7, "x": 5, "y": 1445 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (mode)(increase(rpc_relay_consensusnode_response_count{ namespace=\"$namespace\"}[$__range]))",
       "legendFormat": "{{mode}}"
      }
     ]
    },
    {
     "title": "(WIP) Relay Operator Balance Changes (ℏ)",
     "type": "barchart",
     "gridPos": { "h": 9, "w": 10, "x": 0, "y": 1453 },
     "targets": [
      {
       "expr": "idelta(HIERONET_account_balance{account_id=\"0.0.995584\", network=\"$namespace\"}[$__interval]) / 100000000",
       "legendFormat": "{{accountId}}"
      }
     ]
    },
    {
     "title": "Relay Operator Balance (ℏ)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 14, "x": 10, "y": 1453 },
     "targets": [
      {
       "expr": "avg_over_time(rpc_relay_operator_balance{ namespace=\"$namespace\", mode!=\"QUERY\", mode!=\"TRANSACTION\"}[$__interval]) / 100000000",
       "legendFormat": "{{accountId}}"
      }
     ]
    },
    {
     "title": "Relay Operator Balance Debits (ℏ)",
     "type": "barchart",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1462 },
     "targets": [
      {
       "expr": "sum by(accountId) (idelta(rpc_relay_operator_balance{namespace=\"$namespace\", mode!=\"QUERY\", mode!=\"TRANSACTION\"}[$__interval]) / 100000000)",
       "legendFormat": "{{accountId}}"
      }
     ]
    },
    {
     "title": "(WIP) Relay Operator Balance Changes per day (ℏ)",
     "type": "barchart",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1462 },
     "targets": [
      {
       "expr": "delta(HIERONET_account_balance{account_id=\"0.0.995584\", network=\"$namespace\"}[$__interval]) / 100000000",
       "legendFormat": "{{accountId}}"
      }
     ]
    },
    {
     "title": "(WIP) Relay Operator Balance Changes per day (ℏ)",
     "type": "barchart",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1462 },
     "targets": [
      {
       "expr": "delta(HIERONET_account_balance{account_id=\"0.0.995584\", network=\"$namespace\"}[$__interval]) / 100000000",
       "legendFormat": "{{accountId}}"
      }
     ]
    },
    {
     "title": "Consensus Node Cost Rate by Call (ℏ)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1471 },
     "targets": [
      {
       "expr": "sum by(caller) (rate(rpc_relay_consensusnode_response_sum{ namespace=\"$namespace\"}[$__rate_interval])) / 100000000",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "Consensus Node Cost Rate by Call (ℏ) - test",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1471 },
     "targets": [
      {
       "expr": "sum by(caller) (idelta(rpc_relay_consensusnode_response_sum{namespace=\"$namespace\"}[$__interval])) / 100000000",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "Consensus Node Cost by Call (ℏ)",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 13, "x": 0, "y": 1480 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10,sum by(caller) (increase(rpc_relay_consensusnode_response_sum{ namespace=\"$namespace\"}[$__range])) / 100000000)",
       "legendFormat": " {{caller}}"
      }
     ]
    },
    {
     "title": "Consensus Node Volume by Call ",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 11, "x": 13, "y": 1480 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10,sum by(caller) (increase(rpc_relay_consensusnode_response_count{ namespace=\"$namespace\"}[$__range])))",
       "legendFormat": " {{caller}}"
      }
     ]
    },
    {
     "title": "Hbar Spent By type",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 1489 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(rpc_relay_consensusnode_response_sum{ namespace=\"$namespace\"}[1d])) by(type) / 100000000",
       "legendFormat": "{{mode}}"
      }
     ]
    },
    {
     "title": "Hbar Spent By Mode",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 6, "x": 9, "y": 1489 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(rpc_relay_consensusnode_response_sum{ namespace=\"$namespace\"}[$__range])) by(mode) / 100000000",
       "legendFormat": "{{mode}}"
      }
     ]
    },
    {
     "title": "Hbar Spent By caller",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 9, "x": 15, "y": 1489 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(rpc_relay_consensusnode_response_sum{ namespace=\"$namespace\"}[$__range])) by(caller) / 100000000",
       "legendFormat": "{{mode}}"
      }
     ]
    },
    {
     "title": "HBar spend on FileAppendTransaction",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 1496 },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_consensusnode_response_bucket{mode=\"TRANSACTION\", type=\"FileAppendTransaction\", status=\"SUCCESS\", caller=\"eth_sendRawTransaction\"}[5m])) by (le)\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Hbar Spent per Day over the last Month By Mode",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 9, "y": 1496 },
     "targets": [
      {
       "expr": "sum(increase(rpc_relay_consensusnode_response_sum{ namespace=\"$namespace\"}[1d])) by(mode) / 100000000",
       "legendFormat": "{{mode}}"
      }
     ]
    },
    {
     "title": "Hbar Spent per Day over the last Month By Mode V2",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 15, "y": 1496 },
     "targets": [
      {
       "expr": "avg(delta(rpc_relay_operator_balance{namespace=\"$namespace\", mode!=\"QUERY\", mode!=\"TRANSACTION\"}[1d])) by (accountId) / -100000000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Hbar Spent per Day over the last day By Mode",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1503 },
     "targets": [
      {
       "expr": "sum(increase(rpc_relay_consensusnode_response_sum{ namespace=\"$namespace\"}[30m])) by(mode) / 100000000",
       "legendFormat": "{{mode}}"
      }
     ]
    },
    {
     "title": "Hbar Spent per minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1503 },
     "targets": [
      {
       "expr": "sum(increase(rpc_relay_consensusnode_response_sum{ namespace=\"$namespace\"}[$__rate_interval])) by (pod) / 100000000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Hbar Spent per Day over the last Month by MethodName",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1511 },
     "targets": [
      {
       "expr": "sum(increase(rpc_relay_consensusnode_response_sum{ namespace=\"$namespace\"}[1d])) by(caller) / 100000000",
       "legendFormat": "{{methodName}}"
      }
     ]
    },
    {
     "title": "Hbar Spent per Day over the last Month by Type",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1511 },
     "targets": [
      {
       "expr": "sum(increase(rpc_relay_consensusnode_response_sum{ namespace=\"$namespace\"}[1d])) by(type) / 100000000",
       "legendFormat": "{{methodName}}"
      }
     ]
    },
    {
     "title": "Consensus Node Calls by AccountId/EvmAddress",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1519 },
     "targets": [
      {
       "expr": "topk(10,sum by(interactingEntity)(increase(rpc_relay_consensusnode_response_count{namespace=\"$namespace\", interactingEntity!=\"\"}[$__range])))",
       "legendFormat": "{{interactingEntity}}"
      }
     ]
    },
    {
     "title": "Hbar Spent by AccountId/EvmAddress",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1519 },
     "targets": [
      {
       "expr": "topk(10,sum by(interactingEntity)(increase(rpc_relay_consensusnode_response_sum{namespace=\"$namespace\", interactingEntity!=\"\"}[$__range])) / 100000000)",
       "legendFormat": "{{interactingEntity}}"
      }
     ]
    },
    {
     "title": "Volume of Relay Request by Week",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1530 },
     "targets": [
      {
       "expr": "sum(increase(rpc_relay_method_response_count{ namespace=\"$namespace\"}[$__rate_interval])) / 1000000",
       "legendFormat": "Million of Requests"
      }
     ]
    }
   ]
  },
  {
   "title": "Mirror Node Details - Volume, RPS, Usage and Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg. Latency (ms)",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1036 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(rate(rpc_relay_mirror_response_sum{ namespace=\"$namespace\"}[1m]))/avg(rate(rpc_relay_mirror_response_count{ namespace=\"$namespace\"}[1m]))",
       "legendFormat": "Mirror Node"
      }
     ]
    },
    {
     "title": "Mirror  Node Avg. Latency (ms)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 19, "x": 5, "y": 1036 },
     "targets": [
      {
       "expr": "avg(rate(rpc_relay_mirror_response_sum{ namespace=\"$namespace\"}[1m]))/avg(rate(rpc_relay_mirror_response_count{ namespace=\"$namespace\"}[1m]))",
       "legendFormat": "Mirror Node Avg. Latency"
      }
     ]
    },
    {
     "title": "Mirror Node Latency by Path",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1154 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_mirror_response_sum{ namespace=\"$namespace\"}[1m])) by (method) /\nsum(rate(rpc_relay_mirror_response_count{ namespace=\"$namespace\"}[1m])) by (method)",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "Percentile 90 - Expected Latency for Mirror Node by Method",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1164 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(rpc_relay_mirror_response_bucket{ namespace=\"$namespace\"}[1m])) by (le, method))",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "Percentile 95 - Expected Latency for Mirror Node by Method",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1174 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(rpc_relay_mirror_response_bucket{ namespace=\"$namespace\"}[1m])) by (le, method))",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "Mirror Node RPS",
     "type": "stat",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1184 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_mirror_response_count{ namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "Mirror Node RPS",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 16, "x": 8, "y": 1184 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_mirror_response_count{ namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "Mirror Node RPS",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1194 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_mirror_response_count{ namespace=\"$namespace\"}[$__rate_interval])) by (method)",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "Mirror Node - Requests below 1s",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1204 },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_mirror_response_bucket{ namespace=\"$namespace\", le=\"1000\"}[1m])) by (method)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mirror Node - Requests between 1s and 5s  Latency (Units)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1204 },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_mirror_response_bucket{ namespace=\"$namespace\", le=\"5000\"}[1m]) - ignoring(le) rate(rpc_relay_mirror_response_bucket{namespace=\"$namespace\", le=\"1000\"}[1m])) by (method)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mirror Node - Requests between 5s and 10s Latency (Units)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1213 },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_mirror_response_bucket{ namespace=\"$namespace\", le=\"10000\"}[1m]) - ignoring(le) rate(rpc_relay_mirror_response_bucket{ namespace=\"$namespace\", le=\"5000\"}[1m])) by (method)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mirror Node - Requests between 10s and 20s Latency (Units)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1213 },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_mirror_response_bucket{ namespace=\"$namespace\", le=\"20000\"}[1m]) - ignoring(le) rate(rpc_relay_mirror_response_bucket{ namespace=\"$namespace\", le=\"10000\"}[1m])) by (method)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mirror Node - Requests between 20s and 30s Latency (RPS)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1222 },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_mirror_response_bucket{ namespace=\"$namespace\", le=\"30000\"}[1m]) - ignoring(le) rate(rpc_relay_mirror_response_bucket{ namespace=\"$namespace\", le=\"20000\"}[1m])) by (method)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mirror Node - Requests above 30s Latency (RPS)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1222 },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_mirror_response_bucket{ namespace=\"$namespace\", le=\"+Inf\"}[1m]) - ignoring(le) rate(rpc_relay_mirror_response_bucket{ namespace=\"$namespace\", le=\"30000\"}[1m])) by (method)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mirror Response by Status & Type (RPS)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1231 },
     "targets": [
      {
       "expr": "topk by(statusCode) (5, sum by(statusCode, method) (rate(rpc_relay_mirror_response_count{ namespace=\"$namespace\"}[$__rate_interval])))",
       "legendFormat": "[{{statusCode}}] {{method}}"
      }
     ]
    },
    {
     "title": "Mirror Node RPS by Path",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1241 },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_mirror_response_count{namespace=~\"$namespace\"}[$__rate_interval])) by (method)",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "Mirror Node Contract/Call Calls by StatusCode (Units)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 15, "x": 0, "y": 1251 },
     "targets": [
      {
       "expr": "sum by(statusCode) (increase(rpc_relay_mirror_response_count{ namespace=\"$namespace\", method=\"contracts/call\"}[$__rate_interval]))",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "Mirror Node Contract/Call Calls by StatusCode (%)",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 9, "x": 15, "y": 1251 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(statusCode) (increase(rpc_relay_mirror_response_count{ namespace=\"$namespace\", method=\"contracts/call\"}[$__range]))",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "Mirror Node Contract/Call Calls by StatusCode (RPS)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1262 },
     "targets": [
      {
       "expr": "topk by(statusCode) (10, sum by(statusCode) (rate(rpc_relay_mirror_response_count{ namespace=\"$namespace\", method=\"contracts/call\"}[$__rate_interval])))",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "Mirror Node Calls by StatusCode (RPS)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1272 },
     "targets": [
      {
       "expr": "topk by(statusCode) (10, sum by(statusCode) (rate(rpc_relay_mirror_response_count{ namespace=\"$namespace\"}[$__rate_interval])))",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "Mirror Node Calls by Method",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1282 },
     "targets": [
      {
       "expr": "sum by(method)(increase(rpc_relay_mirror_response_count{ namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "{{ method }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Consensus Node Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 },
   "collapsed": true,
   "panels": [
    {
     "title": "Consensus Node Calls by Status (RPS)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1037 },
     "targets": [
      {
       "expr": "topk by(status) (10, sum by(status) (rate(rpc_relay_consensusnode_response_count{ namespace=\"$namespace\"}[$__rate_interval])))",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "Query Response by Status & Type (RPS)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1087 },
     "targets": [
      {
       "expr": "topk by(status) (10, sum by(status, type) (rate(rpc_relay_consensusnode_response_count{ namespace=\"$namespace\", mode=\"QUERY\"}[$__rate_interval])))",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "Transaction Response by Status",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1097 },
     "targets": [
      {
       "expr": "topk by(status) (10, sum by(status) (rate(rpc_relay_consensusnode_response_count{ namespace=\"$namespace\", mode=\"TRANSACTION\", type=\"EthereumTransaction\"}[$__rate_interval])))",
       "legendFormat": "{{ method }}"
      }
     ]
    }
   ]
  },
  {
   "title": "System Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory",
     "type": "timeseries",
     "description": "Node.js memory",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1038 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(rpc_relay_nodejs_external_memory_bytes{ namespace=\"$namespace\"})",
       "legendFormat": "External"
      },
      {
       "expr": "avg(rpc_relay_process_resident_memory_bytes{ namespace=\"$namespace\"})",
       "legendFormat": "Resident"
      },
      {
       "expr": "avg(rpc_relay_nodejs_heap_size_used_bytes{ namespace=\"$namespace\"})",
       "legendFormat": "Heap Used"
      },
      {
       "expr": "avg(rpc_relay_nodejs_heap_size_total_bytes{ namespace=\"$namespace\"})",
       "legendFormat": "Heap Total"
      }
     ]
    },
    {
     "title": "Current Avg. CPU Usage (%)",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1046 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(rate(rpc_relay_process_cpu_seconds_total{ namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "CPU Usage over Time (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 19, "x": 5, "y": 1046 },
     "targets": [
      {
       "expr": "avg(rate(rpc_relay_process_cpu_seconds_total{namespace=\"$namespace\"}[$__rate_interval]))*100",
       "legendFormat": "Total"
      },
      {
       "expr": "avg(rate(rpc_relay_process_cpu_system_seconds_total{namespace=\"$namespace\"}[$__rate_interval]))*100",
       "legendFormat": "System"
      },
      {
       "expr": "avg(rate(rpc_relay_process_cpu_user_seconds_total{namespace=\"$namespace\"}[$__rate_interval]))*100",
       "legendFormat": "User"
      }
     ]
    },
    {
     "title": "Pod memory usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1054 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_max_usage_bytes{namespace=\"$namespace\", container=\"hedera-json-rpc-relay\"}",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Pod CPU usage rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1062 },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=\"hedera-json-rpc-relay\"}[$__rate_interval])",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Pod Socket count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1070 },
     "targets": [
      {
       "expr": "avg(container_sockets{namespace=\"$namespace\", container=\"hedera-json-rpc-relay\"})",
       "legendFormat": "{{id}}"
      }
     ]
    }
   ]
  }
 ]
}